#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

if [ -z "$DISPLAY" ] && [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -eq 1 ]; then
  exec startx
fi

alias ls='ls --color=auto'

PROMPT_COMMAND='if [ $? = 0 ]; then COLOR="\033[34m"; else COLOR="\033[31m"; fi'
PS1='\w \[$(echo  -ne $COLOR)\]☔\[\033[m\] '

BROWSER=/usr/bin/chromium
EDITOR=/usr/bin/vim

