#! /bin/sh
# To reload this config, just run it.

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         5
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding          28
bspc config active_border_color  "#222222"
bspc config normal_border_color "#222222"
bspc config focused_border_color "#dfdfdf"

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
