#! /bin/sh
# To reload this config, just run it.

bspc monitor -d I II III IV V VI VII VIII IX X

SYS_BLK=$(xrdb -query | sed '/color0/!d' | tail -c 8)
SYS_WHT=$(xrdb -query | sed '/color15/!d' | tail -c 8)

bspc config border_width         3
bspc config window_gap           7

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config top_padding          21
bspc config active_border_color  $SYS_BLK
bspc config normal_border_color  $SYS_BLK
bspc config focused_border_color $SYS_WHT

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
